export const LocalStoreConst = {
  USER_PROFILE: 'USER_PROFILE',
  REFRESH_TOKEN: 'REFRESH_TOKEN',
  LOGIN_STAGE: 'LOGIN_STAGE',
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  USER_CART: 'USER_CART',
  USER_LIBRARY: 'USER_LIBRARY',
  USER_RECOMMEND: 'USER_RECOMMEND',
  USER_WISH_LIST: 'USER_WISH_LIST',
};
